### ISSUE TITLE
Check-Style fails for Google-Style for RightCurlyCheck

### ISSUE THREAD

**Issue by anantdamle** [super-linter/super-linter#4893]
## Describe the bug

Using google_check.xml for Java check-style checking with Google Style fails.
The issue is now fixed with underlying check-style system in version 10.9.0

```
com.puppycrawl.tools.checkstyle.api.CheckstyleException: cannot initialize module TreeWalker - Token "LITERAL_SWITCH" was not found in Acceptable tokens list in check com.puppycrawl.tools.checkstyle.checks.blocks.RightCurlyCheck
        at com.puppycrawl.tools.checkstyle.Checker.setupChild(Checker.java:481)
        at com.puppycrawl.tools.checkstyle.api.AutomaticBean.configure(AutomaticBean.java:201)
        at com.puppycrawl.tools.checkstyle.Main.runCheckstyle(Main.java:412)
        at com.puppycrawl.tools.checkstyle.Main.runCli(Main.java:339)
        at com.puppycrawl.tools.checkstyle.Main.execute(Main.java:196)
        at com.puppycrawl.tools.checkstyle.Main.main(Main.java:131)
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: Token "LITERAL_SWITCH" was not found in Acceptable tokens list in check com.puppycrawl.tools.checkstyle.checks.blocks.RightCurlyCheck
        at com.puppycrawl.tools.checkstyle.TreeWalker.registerCheck(TreeWalker.java:224)
        at com.puppycrawl.tools.checkstyle.TreeWalker.setupChild(TreeWalker.java:134)
        at com.puppycrawl.tools.checkstyle.api.AutomaticBean.configure(AutomaticBean.java:201)
        at com.puppycrawl.tools.checkstyle.Checker.setupChild(Checker.java:476)
        ... 5 more
Checkstyle ends with 1 errors.
```

## Expected behavior

CheckStyle should not fail.

The checkstyle and `google-java-format` versions are not controlled through dependabot and should be.

## Steps to Reproduce

docker run \
  -e RUN_LOCAL=true \
  -e ACTIONS_RUNNER_DEBUG=true \
  -e DISABLE_ERRORS=false \
  -e ERROR_ON_MISSING_EXEC_BIT=true \
  -e LINTER_RULES_PATH=. \
  -e MULTI_STATUS=false \
  -e VALIDATE_ALL_CODEBASE=true \
  -e VALIDATE_JAVA=true \
  -e JAVA_FILE_NAME=google_checks.xml \
  -v $(pwd):/tmp/lint \
  ghcr.io/super-linter/super-linter:v3.13.5

## Additional context

The check-style version is fixed in [Dockerfile](https://github.com/super-linter/super-linter/blob/b335a00df3cef725672b11abba8fa9895f7f06a5/Dockerfile#L37)

**Comment by ferrarimarco** [comment]
#4891 was to handle dependency updates with DependaBot. #4917 is going to fix this.
